language: julia
os:
- linux
- osx
julia:
- 0.7
- nightly
notifications:
  email: false
env:
  global:
  - secure: PUVA2upXeGd7ztEiVksm1zyvQ+300rIEjJwGB6AXy2zavCHbcrUxodkwjGMSF8Voy/6vwR1hVhv2knH8p/m5IG/bQTZAr93DqUWBuuPyHKdcqfyehDsz7q+dMTj7Lmm8XNXNbqDnMRzHJrPSS6/c0MwFhaSIKj/gRsIbGgX9zyxLSM5UKzlM9WTRg9SzlNYdVP3DYFw0s0LkiI13v2n3K9e0CPRfqHVTWEZh/tepPM10JR5zCkWtenAdbr+VhbD4PwuXOOYjwZQgWNR0zeGrtkdgM4Tc2fzNAzDZ+7OLm4PJAu5J1sthwJ+8NrqdaL+2zE4oo4nLI5WerMC85d5z70bEWnHuMwKR1oxH0dmbMPIyuE1KPNux4p8l1qZunqVryc3aX/DHsfMDoFe0IrKln05XswNNkmOwYYQMZFT4F1BvPgtxTjuwwsNepImbKS1iV+YWDdaY+u7VtLDk9gShjQDhQbeGdIF/Jso8YxGz6e258AP+6zn/O2dYFIXJs3ex8Z4jw7+oRLnBiqdMvBUP14F4gRyB79k/2ZWApmPZUkLW+cW1tzxIoUr3iGi85T1bFC9eoU2+tGOz3kLX+PMQJFnnbotXPxf2exDVMxVJM+QTUZ9Xrt8ZOqH+GC2y1Tk3D0AI03IGgqqt0VLUuN0SeT0tasWzZEFRiXxcPqSvOGY=
  - secure: oxM6SAEPP5Dkpaj+REpn2+04j2LahPmdiSwZdW1njoLhC2EDBTziMqLBzvc1WFggQmFySw6RcN15bbGfKq8T0YlBE3Tc5KbUglE7ZTjhvJc5LgBEc6ZAgMhLO2qPs1f0j7EqPIm1FjGfm8eLQgkaqJd91+sb76iv32ayUYy4TlLPbGSUauogKAapc4bJNYRPXukrNyJmUrc7Bf1HAhfPvJPJ5JvN7qwGHmtzuWdT3RSxrifUONYE0WESh/n17GuNicr3Ff5fHmF20CLVqC4gL+Vzgju5CnqW7EVY7YyG1LSmRfVXgMIpJ1upg1oFBXLjldmSdL5oUKL2KTFcrsek9vVzHZZHzHzQZJF3xjsAMw8IFRzFTY7/wmkqpmhnLlnHjEUx2egPlAiCSTagw5Hb8/KX+ujgveHMAIQ4xsacp+rnqudWrOccsvZ81snkA0iBfCXnPihv7CRgoqotNBpWA1/FEpfnQ6pCtPUOCi1f2venLR3W1ez9FJMbdrfEmEbhWjGi6AhwWIVYVry/0tsNqEkTGvNWqYlZtOEILAOsB7i7VJDcDTxecMJDA0hQa9+AMVvGNdysk4c6azYhVyQgeXoJnxe8wcLQEgK8NGP/kQVs6/1GWMHFhnRlS3Fby9TM+3Ke8Ckwt0+5vjiNoXuMu83Nh3COp3MdfgqBaPFkQOo=
matrix:
  allow_failures:
    - julia: nightly
